### ISSUE TITLE
App Idea: Remote Control

### ISSUE THREAD

**Issue by Shadow8472** [Open-Smartwatch/open-smartwatch-os#39] opened 2021-04-22 10:09 UTC
I can see me needing some sort of remote control app for robotics some years down the line. There's no reason it can't be made open enough for other applications. (Sorry, not sure how to add tags)

**Comment by uvwxy** [comment] 2021-04-29 06:47
For simple HTTP calls you can already use 

```c++
    hal->getWiFi()->joinWifi();
    hal->getWiFi()->get("http://192.168.1.118/rgb?r=128&g=0&b=0", httpGetBuffer, 10);  // red 50%
    hal->getWiFi()->disableWiFi();
 ```

I'll close this issue as it's not a bug or a specific request. As the project is open source the best approach for a custom remote would be to write your own. Feel free to discuss this on discord if you need more input on this.

**Closed by uvwxy** 2021-04-29 06:47 UTC
Labels: osw-app
